python run.py --conv "lp"
python run.py --conv "wl"
python run.py --conv "gcn"
python run.py --conv "gat"
python run.py --conv "gin"
python run.py --conv "sgc"
python run.py --conv "mixhop"
python run.py --conv "mixsgc"